name: recursive_reasoning.rf_trm@RF_TRM
loss:
  name: losses@FlowMatchingLossHead

action_dim: 7
chunk_len: 16
obs_dim: 512
hidden_size: 512
num_steps: 16
expansion: 4
num_heads: 8

# Compatibility
puzzle_emb_ndim: 0
pos_encodings: learned
forward_dtype: bfloat16
